// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace DotnetWeb
{

public class BasePage {
  public static IWebDriver driver;

  public void Initialize() {

    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.AddArguments("--start-maximized");
    driver = new ChromeDriver(chromeOptions);
    driver.Url = "https://eksisozluk.com/";
  }

  public void TearDown() {
    driver.Quit();
  }

}

}