// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace DotnetWeb
{

    [TestFixture]
    public class MyTest : BasePage
    {

        HomePage home;

        [OneTimeSetUp]
        public void SetUp()
        {
            Initialize();
            home = new HomePage(driver);
        }

        [Test, Order(1)]
        public void atest()
        {
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(8));

            Assert.That(home.PageLoad(), Is.EqualTo("https://eksisozluk.com/"));
            //String assertText = home.GetPopulerSorular();
            home.SearchBox("dolar");
            Assert.True(home.PageLoad().Contains("dolar"));
            home.Category();

        }

        


        [OneTimeTearDown]
        protected void Close()
        {
            TearDown();
        }

    }

}